I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    define been_outerwalls=FALSE
  File "game/script.rpy", line 7, in <module>
    define been_outerwalls=FALSE
NameError: name 'FALSE' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    define been_outerwalls=FALSE
  File "C:\Users\luigi\Downloads\Programs\renpy-7.3.2-sdk\renpy\ast.py", line 2106, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\luigi\Downloads\Programs\renpy-7.3.2-sdk\renpy\python.py", line 2028, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    define been_outerwalls=FALSE
NameError: name 'FALSE' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
AOT BATTLE OF TROST 1.0
Sat Oct 05 23:51:25 2019
